---
# TODO and best practices http://docs.ansible.com/ansible/playbooks_best_practices.html
- hosts: mac
  vars_files:
    - ./vars/properties.yml
    - ./vars/packages.yml

  tasks:
    - include: ./tasks/osx.yml
      when: ansible_os_family == "Darwin"
      tags:
        - env
    - include: ./tasks/shell.yml
      tags:
        - hack
        - env
    - include: ./tasks/code-tools.yml
      tags:
        - toolbox
        - hack
    - include: ./tasks/vim.yml
      when: editor.name == "vim"
      tags:
        - editor
        - ide
        - toolbox
        - hack
    # NOTE deprecated by docker toolbox : - include: ./tasks/docker.yml
    - include: ./tasks/consul.yml
      when: consul_enabled

    # TODO check or install atom https://atom.io/docs/latest/getting-started-installing-atom
    # TODO check ~/.atom/packages/{{ item }}
    - name: install atom packages
      command: apm install {{ item }}
      with_items: "{{ atom_pkgs }}"
      when: editor == "atom"
      tags:
        - editor
        - ide
        - toolbox
        - hack
