---
# TODO and best practices http://docs.ansible.com/ansible/playbooks_best_practices.html
- hosts: mac
  vars_files:
    - ./vars/properties.yml
    - ./vars/packages.yml

  # TODO there should be a better way than tags[0] == task
  tasks:
    - include: ./tasks/osx.yml
      when: ansible_os_family == "Darwin"
      tags: ["osx", "env"]

    - include: ./tasks/shell.yml
      tags: ["shell", "hack", "env"]

    - include: ./tasks/compilers.yml
      tags: ["compilers", "toolbox", "hack"]

    - include: ./tasks/tools.yml
      tags: ["tools", "toolbox", "hack"]

    - include: ./tasks/vim.yml
      when: editor.name == "vim"
      tags: ["editor", "toolbox", "hack"]

    # NOTE DEPRECATED by docker for Mac : - include: ./tasks/docker.yml

    # TODO install atom thanks to cask
    # TODO check ~/.atom/packages/{{ item }}
    - name: install atom packages
      command: apm install {{ item }}
      with_items: "{{ atom_pkgs }}"
      when: editor == "atom"
      tags: ["editor", "toolbox", "hack"]
