---
- hosts: mac
  vars_files:
    - ./vars/properties.yml
    - ./vars/packages.yml

  tasks:
    - include: ./tasks/shell.yml
    - include: ./tasks/code-tools.yml
    # NOTE deprecated by docker toolbox : - include: ./tasks/docker.yml
    - include: ./tasks/consul.yml
      when: consul_enabled
