---
# TODO and best practices http://docs.ansible.com/ansible/playbooks_best_practices.html
- hosts: machine
  vars_files:
    - ./vars/internal.yml
    - ./vars/settings.yml
    - ./vars/packages.yml
    - ./vars/editor.yml

  tasks:
    - include: ./tasks/osx.yml
      when: ansible_os_family == "Darwin"
      tags: ["osx", "env"]

    - include: ./tasks/linux.yml
      when: ansible_os_family == "Debian"
      tags: ["linux", "env"]

    - include: ./tasks/shell.yml
      tags: ["shell", "hack", "env"]

    - include: ./tasks/compilers.yml
      tags: ["compilers", "toolbox", "hack"]

    - include: ./tasks/tools.yml
      tags: ["tools", "toolbox", "hack"]

    - include: ./tasks/vim.yml
      when: '"vim" in editor.name'
      tags: ["editor", "toolbox", "hack"]

    # NOTE DEPRECATED docker for Mac and docker CE screwed everything...
    # - include: ./tasks/docker.yml