---
# TODO export N_PREFIX also
- name: download tj/n
  git: repo=https://github.com/tj/n dest={{ tmp_path }}/n
- name: install Node version management
  shell: PREFIX={{ dna_home }} make install
  args:
    chdir: "{{ tmp_path }}/n"

# https://github.com/yyuu/pyenv
- name: install pyenv and essential plugins
  shell: curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | PYENV_ROOT="{{ dna_lib_path }}/pyenv" bash

# https://github.com/qw3rtman/gg
- name: install Git Goodies
  shell: curl -fsSL git.io/gg.sh | sh

# https://github.com/rimraf/k
- name: install k, the new l, yo
  get_url: >
    url=https://raw.githubusercontent.com/rimraf/k/master/k.sh
    dest={{ dna_lib_path }}/k.sh

# https://github.com/rupa/z
- name: install z, the new j, yo
  get_url: >
    url=https://raw.githubusercontent.com/rupa/z/master/z.sh
    dest={{ dna_lib_path }}/z.sh

# NOTE what about percol ? (https://github.com/mooz/percol)
# https://github.com/peco/peco
- name: download peco, Simplistic interactive filtering tool
  get_url: >
    url=https://github.com/peco/peco/releases/download/v0.3.3/peco_darwin_amd64.zip
    dest={{ tmp_path }}/peco.zip
- unarchive: src={{ tmp_path }}/peco.zip dest={{ tmp_path }} copy=no
- command: mv {{ tmp_path }}/peco_darwin_amd64/peco {{ dna_bin_path }}/peco

# https://github.com/kennethreitz/autoenv
- name: install autoenv, Directory-based environments
  git: >
    repo=https://github.com/kennethreitz/autoenv
    dest={{ dna_lib_path }}/autoenv
    version=c4bc3f5093f73e5c23563aa5cd66307e2804f35d

# https://github.com/sstephenson/rbenv
- name: install rbenv, ruby version manager
  git: >
    repo=https://github.com/sstephenson/rbenv
    dest={{ dna_lib_path }}/rbenv
    version=9e664b5d27cd7b2bdb94a9ec8ce55c32ebe1ad7a

# https://github.com/sstephenson/ruby-build
- name: install ruby-build
  git: >
    repo=https://github.com/sstephenson/ruby-build
    dest={{ dna_lib_path }}/rbenv/plugins/ruby-build
    version=8d6ff298006994334ac04b1efed098851c63cf4c
