---
# TODO download solarized for terminal
#      or flat : https://github.com/ahmetsulek/flat-terminal

- name: check if homebrew is installed
  command: which brew
  register: is_installed
  failed_when: is_installed.rc > 1
  changed_when: no

- name: install homebrew
  shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: is_installed.rc != 0

- name: brew tap
  homebrew_tap: tap="{{ item }}" state=present
  with_items: "{{ homebrew_taps }}"

- name: Ensure homebrew packages are installed.
  homebrew: name={{ item }} state=present
  with_items: "{{ homebrew_pkgs }} "

- name: Ensure homebrew casks packages are installed.
  homebrew_cask: name={{ item }} state=present
  with_items: "{{ homebrew_casks }} "
  ignore_errors: True
