---
# TODO download solarized for terminal
#      or flat : https://github.com/ahmetsulek/flat-terminal

- name: check if homebrew is installed
  command: which brew
  changed_when: no
  register: brew_check

- name: install homebrew
  shell: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: brew_check.rc != 0

- name: brew tap
  homebrew_tap: tap="{{ item }}" state=present
  with_items: "{{ homebrew_taps }}"

- name: Ensure homebrew packages are installed.
  homebrew: name={{ item }} state=latest
  with_items: "{{ homebrew_pkgs }} "
