---
# NOTE use ansible `before` hook in site.yml ?
- name: create dotfiles head quarters
  file: path={{ dna_home }} state=directory
- file: path={{ dna_home }}/bin state=directory

- name: Set zsh as default shell
  #user: name={{ ansible_ssh_user }} shell=/bin/zsh
  command: chsh -s /bin/zsh
  sudo: yes

# NOTE lightweight alternative : https://github.com/tarjoilija/zgen
- name: install antigen framework
  get_url:
    url=https://raw.githubusercontent.com/zsh-users/antigen/master/antigen.zsh
    dest={{ dna_home }}/antigen.zsh

- name: enable Fish-like autosuggestions for zsh
  git:
    repo=https://github.com/tarruda/zsh-autosuggestions
    dest="{{ dna_lib_path }}/zsh-autosuggestions"

# TODO copy zshrc in dna_home and symlink it in $HOME
- name: copy shell configurations
  template: src=./templates/zshrc.j2 dest={{ ansible_env.HOME }}/.zshrc
- template: src=./templates/plugins.j2 dest={{ dna_home }}/plugins.zsh
- template: src=./templates/shellrc.j2 dest={{ dna_home }}/shellrc

- name: copy tmux configuration
  template: src=./templates/tmux.mac.j2 dest={{ ansible_env.HOME }}/.tmux.conf
# NOTE alternative : https://github.com/tldr-pages/tldr
- name: copy cheatsheets
  copy: src={{ item }} dest={{ ansible_env.HOME }}/.cheat/
  with_fileglob:
    - ./files/cheatsheets/*

- name: copy scripts
  copy: src={{ item }} dest={{ dna_bin_path }}
  with_fileglob:
    - ./files/scripts/*
# NOTE to test : will it copy the directory as-is ?
- name: copy library helpers
  copy: src={{ item }} dest={{ dna_lib_path }}
  with_fileglob:
    - ./files/etc/*

# TODO check if gem is installed (better : use after rbenv installation)
- name: install tmuxinator
  gem: name=tmuxinator state=latest

- name: install spot, tiny search utility
  get_url:
    url=https://raw.github.com/rauchg/spot/master/spot.sh
    dest={{ dna_bin_path }}/spot

- name: install shml, style for terminal
  get_url:
    url=https://raw.githubusercontent.com/MaxCDN/shml/master/shml.sh
    dest={{ dna_lib_path }}/shml.sh

- name: install marker, bookmark your terminal commands
  git:
    repo=https://github.com/pindexis/marker
    dest="{{ dna_lib_path }}/marker"
    version=1a2d9137cd9152043fdad1e11532e12373093b64
- command: ./install.py
  args:
    chdir: "{{ dna_lib_path }}/marker"

- name: download Tmux Plugin Manager
  git:
    repo=https://github.com/tmux-plugins/tpm
    dest="{{ ansible_env.HOME }}/.tmux/plugins/tpm"
    version=f75ba16d5f8276b6f8d08b73f0e2e35a40719251
