---
# https://github.com/qw3rtman/gg
- name: install Git Goodies
  shell: curl -fsSL git.io/gg.sh | sh

# https://github.com/rimraf/k
- name: install k, the new l, yo
  get_url: >
    url=https://raw.githubusercontent.com/rimraf/k/master/k.sh
    dest={{ dna_lib_path }}/k.sh

# https://github.com/rupa/z
- name: install z, the new j, yo
  get_url: >
    url=https://raw.githubusercontent.com/rupa/z/master/z.sh
    dest={{ dna_lib_path }}/z.sh

# NOTE what about percol ? (https://github.com/mooz/percol)
# https://github.com/peco/peco
- name: download peco, Simplistic interactive filtering tool
  get_url: >
    url=https://github.com/peco/peco/releases/download/v0.3.3/peco_darwin_amd64.zip
    dest={{ tmp_path }}/peco.zip
- unarchive: src={{ tmp_path }}/peco.zip dest={{ tmp_path }} copy=no
- command: mv {{ tmp_path }}/peco_darwin_amd64/peco {{ dna_bin_path }}/peco

# https://github.com/kennethreitz/autoenv
- name: install autoenv, Directory-based environments
  git: >
    repo=https://github.com/hackliff/autoenv
    dest={{ dna_lib_path }}/autoenv
    version=040b792c2625c5e73e1a7cf97c5032b631c28b5f

# https://github.com/gleitz/howdoi
- name: install howdoi
  pip: name=howdoi version=1.1.9

# https://github.com/junegunn/fzf
- name: install fzf, fuzzy searcher
  git: repo=https://github.com/junegunn/fzf dest={{ dna_lib_path }}/.fzf
- command: "{{ dna_lib_path }}/.fzf/install --all"

# http://www.jefftk.com/icdiff
- name: install icdiff
  get_url: >
    url=https://raw.githubusercontent.com/jeffkaufman/icdiff/release-1.8.1/icdiff
    dest={{ dna_bin_path }}/icdiff
    mode="ugo+rx"
