---
# TODO execute when editor.version >= 7.4
# download and compile vim 7.4
- name: download vim 7.4
  git: repo=https://github.com/vim/vim
       dest={{ dna_lib_path }}/vim
       version=v7.4.873
- name: compile and install vim
  shell: >
    ./configure
    --with-features=huge
    --enable-multibyte
    --enable-rubyinterp
    --enable-pythoninterp
    --with-python-config-dir=/usr/lib/python2.7/config
    --enable-perlinterp
    --enable-luainterp
    --enable-cscope
    --with-cscope
    --with-lua
    --enable-fail-if-missing
    --with-lua-prefix=/usr/local/Cellar/lua/5.2.4_1
  args:
    chdir: "{{ dna_lib_path }}/vim"
- shell: make VIMRUNTIMEDIR=/usr/local/share/vim/vim74/
  args:
    chdir: "{{ dna_lib_path }}/vim"
- shell: make install
  args:
    chdir: "{{ dna_lib_path }}/vim"

- name: install Vim-plug, Minimalist Vim Plugin Manager
  file: path={{ ansible_env.HOME }}/.vim/autoload state=directory
- file: path={{ ansible_env.HOME }}/.vim/plugins/settings state=directory recurse=yes
- get_url:
    url=https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest={{ ansible_env.HOME }}/.vim/autoload

- name: Copy vimrc configuration file
  template: src=./templates/vimrc.j2 dest={{ ansible_env.HOME }}/.vimrc
# TODO copy an helper like in dna

- name: copy vim plugins configuration
  template: src=./templates/vim-bundles.j2 dest={{ ansible_env.HOME }}/.vim/plugins/bundles.vim

- name: install plugins
  shell: /usr/local/bin/vim +PlugInstall +qall
